repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-json
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ["--maxkb=1000"]

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or: [markdown, json, yaml, javascript]
        exclude: ^cache/

  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--config", ".markdownlint.yaml"]
        exclude: ^cache/

  - repo: https://github.com/JohnnyMorganz/StyLua
    rev: v2.4.0
    hooks:
      - id: stylua
        files: ^dotfiles/nvim/

  - repo: local
    hooks:
      - id: luacheck
        name: luacheck
        entry: luacheck --config dotfiles/nvim/.config/nvim/.luacheckrc
        language: system
        types: [lua]
        files: ^dotfiles/nvim/
