# fonts
font_family CaskaydiaCove Nerd Font
italic_font Hasklig Italic
font_size 17.0

# cursor
cursor_shape block
cursor_stop_blinking_after 0

# scrollback
scrollback_lines 5000
scrollback_pager less --chop-long-lines --RAW-CONTROL-CHARS +INPUT_LINE_NUMBER
scrollback_pager_history_size 100

# mouse
url_color #ed6595
url_style double
detect_urls yes
strip_trailing_spaces smart

# alerts
enable_audio_bell no
visual_bell_duration 0.2
window_alert_on_bell yes

# window
remember_window_size  yes

# tabs
tab_bar_margin_width 5.0
tab_bar_margin_height 5.0 5.0

tab_bar_style powerline
tab_bar_align left

tab_powerline_style slanted
tab_activity_symbol *
tab_title_template " {fmt.fg.red}{bell_symbol}{activity_symbol}{fmt.fg.tab}{title} "

active_tab_foreground   #ed6595
active_tab_background   #e0e4e5
active_tab_font_style   bold

inactive_tab_foreground #e0e4e5
inactive_tab_background #7e8892
inactive_tab_font_style normal

# colors
selection_foreground #000000
selection_background #e0e4e5

# os specific
macos_option_as_alt all
macos_thicken_font 0.35

# keyboard shortcuts
map cmd+t new_tab_with_cwd
map cmd+1 goto_tab 1
map cmd+2 goto_tab 2
map cmd+3 goto_tab 3
map cmd+4 goto_tab 4
map cmd+5 goto_tab 5
map cmd+6 goto_tab 6
map cmd+7 goto_tab 7
map cmd+8 goto_tab 8
map cmd+9 goto_tab 9

# shell integration
shell_integration disabled
