#:schema https://docs.jj-vcs.dev/latest/config-schema.json

[user]
name = "Trevor Strieber"
email = "trevor@strieber.org"

[ui]
default-command = "status"
pager = ["delta", "--dark"]
diff.format = "git"
editor = "nvim"
diff-editor = ":builtin"

[merge-tools.difft]
program = "difft"
diff-args = ["--color=always", "--display=inline", "$left", "$right"]

[colors]
"added" = { fg = "green", bold = true }
"modified" = { fg = "yellow", bold = false }
"removed" = { fg = "red", bold = true }
"diff removed token" = { fg = "bright red", bg = "#400000", underline = false }
"diff added token" = { fg = "bright green", bg = "#003000", underline = false }

[aliases]
s = ["status"]
l = ["log", "-n", "15"]
la = ["log", "--revsets", "all()"]
lb = ["log", "-r", "trunk()..@"]
e = ["evolog"]
d = ["diff"]
ds = ["diff", "--stat"]
dd = ["diff", "--tool", "difft"]
f = ["git", "fetch"]
pull = ["git", "fetch", "--branch"]
push = ["git", "push"]
b = ["bookmark", "list"]
tug = ["bookmark", "move", "--from", "heads(::@- & bookmarks())", "--to", "@-"]

[remotes.origin]
auto-track-bookmarks = "glob:*"

[revsets]
bookmark-advance-from = "bookmarks()"
bookmark-advance-to = "@"

[revset-aliases]
'immutable_heads()' = 'builtin_immutable_heads() | remote_bookmarks()'
